//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graff.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class testeRodrigo_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string DS_NOME_USUARIO { get; set; }
        public Nullable<System.DateTime> DT_NASCIMENTO_USUARIO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO_USUARIO { get; set; }
        public string DS_EMAIL_USUARIO { get; set; }
        public string DS_SENHA_USUARIO { get; set; }
    }
}
