//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graff.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class testeRodrigo_PRODUTO
    {
        public int ID_PRODUTO { get; set; }
        public string DS_NOME_PRODUTO { get; set; }
        public Nullable<System.DateTime> DT_INCLUSAO_PRODUTO { get; set; }
        public string DS_PRODUTO { get; set; }
        public Nullable<decimal> VL_LANCE_INICIAL { get; set; }
    }
}
