//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Graff.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class testeRodrigo_LANCES
    {
        public int ID_LANCE { get; set; }
        public Nullable<int> ID_USUARIO { get; set; }
        public Nullable<int> ID_PRODUTO { get; set; }
        public Nullable<decimal> VL_LANCE_ANTERIOR { get; set; }
        public Nullable<decimal> VL_LANCE_ATUAL { get; set; }
        public Nullable<System.DateTime> DT_LANCE { get; set; }
    }
}
