/****** Object:  Table [dbo].[testeRodrigo_PRODUTO]    Script Date: 17/02/2021 19:15:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[testeRodrigo_PRODUTO](
	[ID_PRODUTO] [int] IDENTITY(1,1) NOT NULL,
	[DS_NOME_PRODUTO] [varchar](200) NULL,
	[DT_INCLUSAO_PRODUTO] [datetime] NULL,
	[DS_PRODUTO] [varchar](200) NULL,
	[VL_LANCE_INICIAL] [numeric](10, 2) NULL,
 CONSTRAINT [PK_testeRodrigo_PRODUTO] PRIMARY KEY CLUSTERED 
(
	[ID_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


