/****** Object:  Table [dbo].[testeRodrigo_LANCES]    Script Date: 17/02/2021 19:15:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[testeRodrigo_LANCES](
	[ID_LANCE] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NULL,
	[ID_PRODUTO] [int] NULL,
	[VL_LANCE_ANTERIOR] [numeric](10, 2) NULL,
	[VL_LANCE_ATUAL] [numeric](10, 2) NULL,
	[DT_LANCE] [datetime] NULL,
 CONSTRAINT [PK_testeRodrigo_LANCES] PRIMARY KEY CLUSTERED 
(
	[ID_LANCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


