/****** Object:  Table [dbo].[testeRodrigo_USUARIO]    Script Date: 17/02/2021 19:15:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[testeRodrigo_USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[DS_NOME_USUARIO] [varchar](200) NULL,
	[DT_NASCIMENTO_USUARIO] [date] NULL,
	[DT_INCLUSAO_USUARIO] [datetime] NULL,
	[DS_EMAIL_USUARIO] [varchar](200) NULL,
	[DS_SENHA_USUARIO] [varchar](20) NULL,
 CONSTRAINT [PK_testeRodrigo_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


